apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: compress-app
  name: compress-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compress-app
  template:
    metadata:
      labels:
        app: compress-app
    spec:
      containers:
      - image: haoranq4/compress:latest
        imagePullPolicy: IfNotPresent
        name: compress-container
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: compress-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: compress-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30002
